name: cvaetf1
channels:
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.11.0
  - alabaster=0.7.12
  - applaunchservices=0.2.1
  - appnope=0.1.2
  - argh=0.26.2
  - astor=0.8.1
  - astroid=2.3.3
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=20.3.0
  - autopep8=1.5.4
  - babel=2.9.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.2.1
  - brotlipy=0.7.0
  - c-ares=1.17.1
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=4.0.0
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - cryptography=3.3.1
  - cycler=0.10.0
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.6.0
  - diff-match-patch=20200713
  - dill=0.3.3
  - docutils=0.16
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - expat=2.2.10
  - flake8=3.8.4
  - freetype=2.10.4
  - future=0.18.2
  - gast=0.2.2
  - gettext=0.19.8.1
  - glib=2.67.4
  - google-pasta=0.2.0
  - grpcio=1.31.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=2.10
  - imagesize=1.2.0
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2019.4
  - intervaltree=3.1.0
  - ipykernel=5.3.4
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - isort=5.6.4
  - jdcal=1.4.1
  - jedi=0.17.1
  - jinja2=2.11.2
  - joblib=1.0.0
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - keyring=21.7.0
  - kiwisolver=1.3.0
  - lazy-object-proxy=1.5.2
  - lcms2=2.11
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgfortran=3.0.1
  - libiconv=1.16
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libtiff=4.1.0
  - llvm-openmp=10.0.0
  - lz4-c=1.9.3
  - markdown=3.3.3
  - markupsafe=1.1.1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - numpy=1.19.2
  - numpy-base=1.19.2
  - numpydoc=1.1.0
  - olefile=0.46
  - openpyxl=3.0.5
  - openssl=1.1.1j
  - opt_einsum=3.1.0
  - packaging=20.8
  - pandas=1.1.5
  - pandoc=2.11
  - pandocfilters=1.4.3
  - parso=0.7.0
  - pathtools=0.1.2
  - patsy=0.5.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.3.3
  - pluggy=0.13.1
  - prompt-toolkit=3.0.8
  - protobuf=3.13.0
  - psutil=5.7.2
  - ptyprocess=0.6.0
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pydocstyle=5.1.1
  - pyflakes=2.2.0
  - pygments=2.7.3
  - pylint=2.3.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.7.10
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.4.0
  - python-language-server=0.35.1
  - python.app=3
  - pytz=2020.4
  - pyyaml=5.3.1
  - pyzmq=20.0.0
  - qdarkstyle=2.8.1
  - qt=5.9.7
  - qtawesome=1.0.1
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - readline=8.1
  - requests=2.25.1
  - rope=0.18.0
  - rtree=0.9.4
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.0
  - setuptools=52.0.0
  - sip=4.19.8
  - six=1.15.0
  - snowballstemmer=2.0.0
  - sortedcontainers=2.3.0
  - sphinx=3.4.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - spyder=4.1.5
  - spyder-kernels=1.9.4
  - sqlite=3.33.0
  - statsmodels=0.12.1
  - tensorboard=1.15.0
  - tensorflow=1.15.0
  - tensorflow-base=1.15.0
  - tensorflow-estimator=1.15.1
  - termcolor=1.1.0
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.1
  - tornado=6.1
  - tqdm=4.54.1
  - traitlets=5.0.5
  - ujson=4.0.1
  - urllib3=1.26.2
  - watchdog=0.10.4
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=0.16.1
  - wheel=0.36.2
  - wrapt=1.12.1
  - wurlitzer=2.0.1
  - xlrd=2.0.1
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.30.0
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - lxml==4.6.2
    - pandas-datareader==0.9.0
    - pickle5==0.0.11

