name: RBM
channels:
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.12.0
  - alabaster=0.7.12
  - appdirs=1.4.4
  - applaunchservices=0.2.1
  - appnope=0.1.2
  - argh=0.26.2
  - astor=0.8.1
  - astroid=2.5
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=20.3.0
  - autopep8=1.5.6
  - babel=2.9.0
  - backcall=0.2.0
  - black=19.3b0
  - blas=1.0
  - bleach=3.3.0
  - brotlipy=0.7.0
  - c-ares=1.17.1
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - click=7.1.2
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - coverage=5.5
  - cryptography=3.4.7
  - cycler=0.10.0
  - cython=0.29.22
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - docutils=0.16
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - expat=2.3.0
  - flake8=3.9.0
  - freetype=2.10.4
  - future=0.18.2
  - gast=0.2.2
  - gettext=0.19.8.1
  - glib=2.68.0
  - google-pasta=0.2.0
  - grpcio=1.36.1
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=2.10
  - imagesize=1.2.0
  - importlib-metadata=3.7.3
  - importlib_metadata=3.7.3
  - intervaltree=3.1.0
  - ipykernel=5.3.4
  - ipython=7.21.0
  - ipython_genutils=0.2.0
  - isort=5.8.0
  - jdcal=1.4.1
  - jedi=0.17.2
  - jinja2=2.11.3
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - keyring=22.3.0
  - kiwisolver=1.3.1
  - lazy-object-proxy=1.6.0
  - lcms2=2.11
  - libcxx=10.0.0
  - libffi=3.3
  - libgfortran=3.0.1
  - libiconv=1.16
  - libopenblas=0.3.13
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=1.1.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mccabe=0.6.1
  - mistune=0.8.4
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - numpy=1.19.2
  - numpy-base=1.19.2
  - numpydoc=1.1.0
  - olefile=0.46
  - openpyxl=3.0.7
  - openssl=1.1.1k
  - opt_einsum=3.1.0
  - packaging=20.9
  - pandas=1.2.3
  - pandoc=2.12
  - pandocfilters=1.4.3
  - parso=0.7.0
  - patsy=0.5.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.2
  - pip=21.0.1
  - pluggy=0.13.1
  - prompt-toolkit=3.0.17
  - protobuf=3.14.0
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pydocstyle=6.0.0
  - pyflakes=2.2.0
  - pygments=2.8.1
  - pylint=2.7.2
  - pyls-black=0.4.6
  - pyls-spyder=0.3.2
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.7.10
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.4.0
  - python-language-server=0.36.2
  - python.app=3
  - pytz=2021.1
  - pyyaml=5.4.1
  - pyzmq=20.0.0
  - qdarkstyle=2.8.1
  - qt=5.9.7
  - qtawesome=1.0.2
  - qtconsole=5.0.3
  - qtpy=1.9.0
  - readline=8.1
  - requests=2.25.1
  - rope=0.18.0
  - rtree=0.9.4
  - scipy=1.6.2
  - seaborn=0.11.1
  - setuptools=52.0.0
  - sip=4.19.8
  - six=1.15.0
  - snowballstemmer=2.1.0
  - sortedcontainers=2.3.0
  - sphinx=3.5.3
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - spyder=4.2.5
  - spyder-kernels=1.10.2
  - sqlite=3.35.2
  - statsmodels=0.12.2
  - tensorboard=2.0.0
  - tensorflow=2.0.0
  - tensorflow-base=2.0.0
  - tensorflow-estimator=2.0.0
  - termcolor=1.1.0
  - testpath=0.4.4
  - textdistance=4.2.1
  - three-merge=0.1.1
  - tk=8.6.10
  - toml=0.10.2
  - tornado=6.1
  - tqdm=4.59.0
  - traitlets=5.0.5
  - typed-ast=1.4.2
  - typing_extensions=3.7.4.3
  - tzdata=2020f
  - ujson=4.0.2
  - urllib3=1.26.4
  - watchdog=1.0.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.36.2
  - wrapt=1.12.1
  - wurlitzer=2.0.1
  - xlrd=2.0.1
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.31.0
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - deepdish==0.3.6
    - joblib==1.0.1
    - lxml==4.6.3
    - numexpr==2.7.3
    - pandas-datareader==0.9.0
    - pickle5==0.0.11
    - scikit-learn==0.24.1
    - sklearn==0.0
    - tables==3.6.1
    - threadpoolctl==2.1.0

